filebeat.inputs:
- type: filestream
  id: {{ component }}
  enabled: true
  paths:
    - {{ log_file }}              # lofile for logs

  fields:
    component: {{ component }}    # name which will be created in elk for each service

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["172.31.61.30:5044"]    # connecting to elk server

# default config
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

processors:
  - drop_fields:
      fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.type", "agent.version", "ecs.version", "input.type", "log.offset", "version", "agent.name"]
