filebeat.inputs:
- type: filestream
  id: {{ component }}
  enabled: true
  paths:
    - {{ log_file }}              # lofile for logs

  fields:
    component: {{ component }}    # name which will be created in elk for each service

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["172.31.61.30:5044"]    # connecting to elk server

# default config
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
