- name: install nginx
  ansible.builtin.yum:                  # yum module to install softwares
    name: nginx
    state: installed

- name: copying roboshop.conf file
  ansible.builtin.template: # template is used to copy same as copy module. but the diff is when passing values dynamic
    src: roboshop.conf      # the values will be replaced using templates. but in copy it will not
    dest: /etc/nginx/default.d/roboshop.conf

- name: copying nginx.conf file
  ansible.builtin.template:
    src: nginx.conf                   # copying nginx.conf file
    dest: /etc/nginx/nginx.conf

- name: removing the existing content available in the below location
  ansible.builtin.file:                 # file module to delete paths
    path: /usr/share/nginx/html
    state: absent

- name: create new app directory
  ansible.builtin.file:                 # file module to create paths
    path: /usr/share/nginx/html
    state: directory

- name: download the application code
  ansible.builtin.unarchive:              # downloads the contents from url and unzips it
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes                       # download the content from internet

- name: restarting nginx
  ansible.builtin.service:                # service module to star stop restart
    name: nginx
    state: restarted
    enabled: yes

- name: Import File beat
  ansible.builtin.import_role:
    name: elk                            # importing the role elk
    tasks_from: filebeat                 # importing the task filebeat from elk role

