- name: install maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Importing task app_prereq.yml
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: download the dependencies and build application
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: Importing task schema_setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Importing task systemd_setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
