- name: created the {{component}} service and copying it
  ansible.builtin.template:         # template is for copy and its used for dynamic passing values
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: start {{component}} service
  ansible.builtin.systemd:        # staring the service systemd module
    name: "{{component}}"
    state: restarted
    daemon-reload: true           # deamon-reload config
    enabled: true

  